# If you change this version, change the numbers in .github/workflows/ci-emscripten.yml (2x)
# and .github/workflows/preview-build.yml (2x) too.
FROM emscripten/emsdk:3.1.57

COPY ports/liblzma.py /emsdk/upstream/emscripten/tools/ports/contrib/liblzma.py
